'use strict';

export default {
  NAVIGATE_INITIAL:              'NAVIGATE_INITIAL',
  NAVIGATE_LIST_OF_BEVERAGE:     'NAVIGATE_LIST_OF_BEVERAGE',
  LOAD_LIST_OF_BEVERAGE:         'LOAD_LIST_OF_BEVERAGE',
  NAVIGATE_LIST_OF_COFFEE_TYPES: 'NAVIGATE_LIST_OF_COFFEE_TYPES',
  LOAD_LIST_OF_COFFEE_TYPES:     'LOAD_LIST_OF_COFFEE_TYPES',
  SELECT_BEVERAGE:               'SELECT_BEVERAGE',
  NAVIGATE_ORDER_BEVERAGE:       'NAVIGATE_ORDER_BEVERAGE',
  ORDER_BEVERAGE:                'ORDER_BEVERAGE',
  NAVIGATE_SUCCESS:              'NAVIGATE_SUCCESS',
  NAVIGATE_FAIL:                 'NAVIGATE_FAIL',
}